### ISSUE TITLE
error a nil value

### ISSUE THREAD

**Issue by karnakkobalos** [T-Rizzle12/Custom-Gmod-Bot#59]
Je suis en mode Dark RP et j'essaye d'utiliser votre script afin de faire des test sur vos bots.

Hélas, au moment où je nomme le bot, ma console est spammée d'erreur : 

[Custom Gmod Bot] lua/autorun/server/trizzlebot_base.lua:5665: attempt to compare number with nil
  1. TBotFindHealTarget - lua/autorun/server/trizzlebot_base.lua:5665
   2. func - lua/autorun/server/trizzlebot_base.lua:3885
    3. unknown - lua/includes/modules/hook.lua:247

[Custom Gmod Bot] lua/autorun/server/trizzlebot_base.lua:4214: attempt to perform arithmetic on field 'FollowDist' (a nil value)
  1. TBotIdleState - lua/autorun/server/trizzlebot_base.lua:4214
   2. func - lua/autorun/server/trizzlebot_base.lua:3991
    3. unknown - lua/includes/modules/hook.lua:247

Je précise que lorsque je créer un bot sans nom "unnamed", il fonctionne très bien sans générer d'erreur. Pouvez-vous m'aider ?

**Comment by T-Rizzle12** [comment]
Ok, I looked into your issue, and it appears to be because the bot isn't properly initialized. You should only create bots using the TBotCreate function, TRizzleBotCreateMenu, and the TRizzleCreateBot console command. Since it appears that you only need to name the bot I will show you how to use the bot properly.

1. The TRizzleCreateBot console command: 
TRizzleCreateBot is a very complex command but only requires one of the many parameters the bot's name.
In your console just enter the following "TRizzleCreateBot <botname>"
Here is an example: TRizzleCreateBot "Alyx Vance"

2. The TRizzleBotCreateMenu console command:
This is the easiest way to create a bot use fill in the information on the vgui and you should be go to go.

3. The TBotCreate function:
I don't recommend creating a bot this way, but if you have to. Here is some code that will I hope do what you intend to do.
`TBotCreate( Entity(1), "TBotCreate", { "Alyx Vance" } )`
You can change the name in the table to whatever you want.

Please let me know if you try all three solutions and still encounter the error!

**Comment by T-Rizzle12** [comment]
It's been a while since there was any activity on this issue, so I don't have enough info to fix the issue that you are experiencing. If this was made in error, please let me know.
